Fix compile warnings
RobotWebTools/web_video_server pull request #176
Opened 2024-12-20 13:38 UTC by Mat198

Enabling compile warnings as errors to avoid future bugs.

My current job require these flags on so I thoght it would be nice to include these little changes here. 

Hope it helps.

2024-12-21 21:12 UTC, bjsowa requested changes
I appreciate the effort but would you mind removing the Werror option? I'm not a fan of it as it creates a dependency on specific toolchain versions.

2024-12-21 21:12 UTC, bjsowa commented on src/libav_streamer.cpp
```suggestion
```
cpplint complains about blank line here

2024-12-26 19:13 UTC, Mat198 commented
> I appreciate the effort but would you mind removing the Werror option? I'm not a fan of it as it creates a dependency on specific toolchain versions.

Flag removed

2024-12-26 20:14 UTC, bjsowa approved these changes

2024-12-26 20:15 UTC, merged