Adding optional frame skipping for streamer
RobotWebTools/web_video_server pull request #37
Opened 2017-08-15 18:34 UTC by r3n33

With the HTTP request for an image a 'skip_frames' parameter can be specified to reduce the number of frames streamed over the network.

2017-08-30 07:25 UTC, jihoonl requested changes
1. `frames_skipped_` variable is used without initialization.
2. How about having `frame_rate` instead instead of skipping `x` number of frames? Then, we can control streaming rate regardless of topic subscription frequency

2017-08-30 07:25 UTC, jihoonl commented on include/web_video_server/image_streamer.h
> +  int frames_skipped_;
Initialise this variable.

2018-01-08 04:01 UTC, jihoonl commented
This PR has been inactive for a long time. Please reopen when it is ready again.

2018-01-08 04:01 UTC, closed without merging

2019-06-11 22:11 UTC, 130s commented
Related,

I think skipping frame might be not as bad it may sound, as ROS' subscriber implementation AFAIK doesn't have control over the subscription rate (e.g. [answers.ros.org#q240768](http://answers.ros.org/question/240768/how-can-the-subscriber-subscribe-once-every-2-seconds/)). I added a customization example on the wiki [wiki.ros.org/web_video_server](http://wiki.ros.org/action/info/web_video_server?action=diff&rev2=8&rev1=7).